# Generated by Django 6.0.3 on 2026-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_key', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Rice', 'Rice'), ('Meat', 'Meat'), ('Vegetable', 'Vegetable')], max_length=20)),
                ('rating', models.FloatField(default=0.0)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
    ]
