# Generated by Django 6.0.5 on 2026-05-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_key',
            field=models.CharField(default='default_category', help_text="Key for local asset mapping (e.g., 'breakfast')", max_length=50),
        ),
    ]
