# Generated by Django 6.0.3 on 2026-05-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_ingredients_recipe_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Meat', 'Meat'), ('Vegetable', 'Vegetable'), ('Seafood', 'Seafood')], max_length=20),
        ),
    ]
